--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      HP Inc.
-- Project :      ProyectoBDA.DM1
-- Author :       Windows User
--
-- Date Created : Monday, February 01, 2021 23:44:40
-- Target DBMS : Oracle 11g
--

-- 
-- TABLESPACE: BLOB_TBS 
--

CREATE TABLESPACE BLOB_TBS
    DATAFILE '/disco/disco01/blob/datafile.dbf' SIZE 1024M AUTOEXTEND ON NEXT 102400K MAXSIZE 2097152K
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    LOGGING
    ONLINE
    SEGMENT SPACE MANAGEMENT AUTO
;

-- 
-- TABLESPACE: CLIENTE_TBS 
--

CREATE TABLESPACE CLIENTE_TBS
    DATAFILE '/disco/disco01/cliente/datafile.dbf' SIZE 1024M AUTOEXTEND ON NEXT 102400K MAXSIZE 2097152K
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    LOGGING
    ONLINE
    SEGMENT SPACE MANAGEMENT AUTO
;

-- 
-- TABLESPACE: EMPLEADO_TBS 
--

CREATE TABLESPACE EMPLEADO_TBS
    DATAFILE '/disco/disco01/empleado/datafile.dbf' SIZE 1024M AUTOEXTEND ON NEXT 102400K MAXSIZE 2097152K
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    LOGGING
    ONLINE
    SEGMENT SPACE MANAGEMENT AUTO
;

-- 
-- TABLESPACE: INFRAESTRUCTURA_TBS 
--

CREATE TABLESPACE INFRAESTRUCTURA_TBS
    DATAFILE '/disco/disco01/infraestructura/datafile.dbf' SIZE 1024M AUTOEXTEND ON NEXT 102400K MAXSIZE 2097152K
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE
    LOGGING
    ONLINE
    SEGMENT SPACE MANAGEMENT AUTO
;

-- 
-- ROLE: ROL_ADMINISTRACION 
--

CREATE ROLE ROL_ADMINISTRACION NOT IDENTIFIED
;

-- 
-- USER: USER_CLIENTE 
--

CREATE USER USER_CLIENTE IDENTIFIED BY VALUES 'cliente'
    DEFAULT TABLESPACE CLIENTE_TBS
    QUOTA UNLIMITED ON CLIENTE_TBS
;

-- 
-- USER: USER_EMPLEADO 
--

CREATE USER USER_EMPLEADO IDENTIFIED BY VALUES 'empleado'
    DEFAULT TABLESPACE EMPLEADO_TBS
;

-- 
-- USER: USER_INFRAESTRUCTURA 
--

CREATE USER USER_INFRAESTRUCTURA IDENTIFIED BY VALUES 'admin'
    DEFAULT TABLESPACE INFRAESTRUCTURA_TBS
;

-- 
-- SEQUENCE: USER_CLIENTE.SEQ_BITACORA 
--

CREATE SEQUENCE USER_CLIENTE.SEQ_BITACORA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_CLIENTE.SEQ_CLIENTE 
--

CREATE SEQUENCE USER_CLIENTE.SEQ_CLIENTE
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_CLIENTES_GIMNASIO 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_CLIENTES_GIMNASIO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_DISCIPLINA 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_DISCIPLINA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_DISPOSITIVO 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_DISPOSITIVO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_DISPOSITIVO_SESION 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_DISPOSITIVO_SESION
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_EMPLEADO.SEQ_EMPLEADO 
--

CREATE SEQUENCE USER_EMPLEADO.SEQ_EMPLEADO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_GIMNASIO 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_GIMNASIO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_HISTORICO_STATUS_DISP 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_HISTORICO_STATUS_DISP
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_MULTIMEDIA 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_MULTIMEDIA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_EMPLEADO.SEQ_PUESTO 
--

CREATE SEQUENCE USER_EMPLEADO.SEQ_PUESTO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_CLIENTE.SEQ_REPORTE_FISICO 
--

CREATE SEQUENCE USER_CLIENTE.SEQ_REPORTE_FISICO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_SALA 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_SALA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_SALA_DISCIPLINA 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_SALA_DISCIPLINA
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_CLIENTE.SEQ_SENSOR 
--

CREATE SEQUENCE USER_CLIENTE.SEQ_SENSOR
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_CLIENTE.SEQ_SESION 
--

CREATE SEQUENCE USER_CLIENTE.SEQ_SESION
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_STATUS_DISPOSITIVO 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_STATUS_DISPOSITIVO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_INFRAESTRUCTURA.SEQ_TIPO_DISPOSITIVO 
--

CREATE SEQUENCE USER_INFRAESTRUCTURA.SEQ_TIPO_DISPOSITIVO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- SEQUENCE: USER_EMPLEADO.SEQ_URL 
--

CREATE SEQUENCE USER_EMPLEADO.SEQ_URL
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;

-- 
-- TABLE: USER_ADMINISTRADOR.CLIENTES_GIMNASIO 
--

CREATE TABLE USER_ADMINISTRADOR.CLIENTES_GIMNASIO(
    CLIENTE_GIMNASIO_ID    NUMBER(10, 0)    NOT NULL,
    GIMNASIO_ID            NUMBER(10, 0)    NOT NULL,
    CLIENTE_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CLIENTES_GIMNASIO_PK PRIMARY KEY (CLIENTE_GIMNASIO_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.DISCIPLINA 
--

CREATE TABLE USER_ADMINISTRADOR.DISCIPLINA(
    DISCIPLINA_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE            VARCHAR2(10)     NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(255)    NOT NULL,
    ICONO            BLOB             NOT NULL,
    CONSTRAINT DISCIPLINA_PK PRIMARY KEY (DISCIPLINA_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.DISPOSITIVO 
--

CREATE TABLE USER_ADMINISTRADOR.DISPOSITIVO(
    DISPOSITIVO_ID           NUMBER(10, 0)    NOT NULL,
    NUM_INVENTARIO           VARCHAR2(18)     NOT NULL,
    FECHA_ADQUISICION        DATE             NOT NULL,
    FECHA_STATUS             DATE             NOT NULL,
    TIPO_DISPOSITIVO_ID      NUMBER(10, 0)    NOT NULL,
    SALA_ID                  NUMBER(10, 0)    NOT NULL,
    STATUS_DISPOSITIVO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT DISPOSITIVO_PK PRIMARY KEY (DISPOSITIVO_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.GIMNASIO 
--

CREATE TABLE USER_ADMINISTRADOR.GIMNASIO(
    GIMNASIO_ID    NUMBER(10, 0)    NOT NULL,
    FOLIO          VARCHAR2(5)      NOT NULL,
    NOMBRE         VARCHAR2(40)     NOT NULL,
    DIRECCION      VARCHAR2(255)    NOT NULL,
    LATITUD        NUMBER(8, 5)     NOT NULL,
    LONGITUD       NUMBER(8, 5)     NOT NULL,
    TELEFONO       VARCHAR2(10)     NOT NULL,
    PAGINA_WEB     VARCHAR2(255)    NOT NULL,
    EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT GIMNASIO_PK PRIMARY KEY (GIMNASIO_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.HISTORICO_STATUS_DISPOSITIVO 
--

CREATE TABLE USER_ADMINISTRADOR.HISTORICO_STATUS_DISPOSITIVO(
    HISTORICO_STATUS_DISPOSITIVO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                       DATE             NOT NULL,
    STATUS_DISPOSITIVO_ID              NUMBER(10, 0)    NOT NULL,
    DISPOSITIVO_ID                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT HISTORICO_STATUS_DISPOSITIVO_PK PRIMARY KEY (HISTORICO_STATUS_DISPOSITIVO_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.MULTIMEDIA 
--

CREATE TABLE USER_ADMINISTRADOR.MULTIMEDIA(
    MULTIMEDIA_ID    NUMBER(10, 0)    NOT NULL,
    ARCHIVO          BLOB             NOT NULL,
    TIPO_ARCHIVO     CHAR(1)          NOT NULL,
    VIGENCIA         DATE             NOT NULL,
    GIMNASIO_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT MULTIMEDIA_PK PRIMARY KEY (MULTIMEDIA_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.SALA 
--

CREATE TABLE USER_ADMINISTRADOR.SALA(
    SALA_ID          NUMBER(10, 0)    NOT NULL,
    CLAVE            VARCHAR2(3)      NOT NULL,
    NOMBRE           VARCHAR2(40)     NOT NULL,
    CAPACIDAD_MAX    NUMBER(3, 0)     NOT NULL,
    GIMNASIO_ID      NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT SALA_PK PRIMARY KEY (SALA_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.SALA_DISCIPLINA 
--

CREATE TABLE USER_ADMINISTRADOR.SALA_DISCIPLINA(
    SALA_DISCIPLINA    NUMBER(10, 0)    NOT NULL,
    SALA_ID            NUMBER(10, 0)    NOT NULL,
    DISCIPLINA_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK23 PRIMARY KEY (SALA_DISCIPLINA)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.STATUS_DISPOSITIVO 
--

CREATE TABLE USER_ADMINISTRADOR.STATUS_DISPOSITIVO(
    STATUS_DISPOSITIVO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE                    VARCHAR2(10)     NOT NULL,
    DESCRIPCION              VARCHAR2(255)    NOT NULL,
    CONSTRAINT STATUS_DISPOSITIVO_PK PRIMARY KEY (STATUS_DISPOSITIVO_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.TIPO_DISPOSITIVO 
--

CREATE TABLE USER_ADMINISTRADOR.TIPO_DISPOSITIVO(
    TIPO_DISPOSITIVO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION            VARCHAR2(255)    NOT NULL,
    CONSTRAINT TIPO_DISPOSITIVO_PK PRIMARY KEY (TIPO_DISPOSITIVO_ID)
)
;



-- 
-- TABLE: USER_CLIENTE.BITACORA 
--

CREATE TABLE USER_CLIENTE.BITACORA(
    BITACORA_ID            NUMBER(10, 0)    NOT NULL,
    CALORIAS_CONSUMIDAS    NUMBER(6, 0)     NOT NULL,
    FECHA_HORA_REGISTRO    DATE             NOT NULL,
    SESION_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT BITACORA_PK PRIMARY KEY (BITACORA_ID)
)
;



-- 
-- TABLE: USER_CLIENTE.CLIENTE 
--

CREATE TABLE USER_CLIENTE.CLIENTE(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40),
    EMAIL               VARCHAR2(100)    NOT NULL,
    USERNAME            VARCHAR2(40)     NOT NULL,
    PASSWORD            VARCHAR2(255)    NOT NULL,
    DIRECCION           VARCHAR2(255)    NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    FOTO                BLOB             NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: USER_CLIENTE.CREDENCIAL_CLIENTE 
--

CREATE TABLE USER_CLIENTE.CREDENCIAL_CLIENTE(
    CLIENTE_ID       NUMBER(10, 0)    NOT NULL,
    VIGENCIA         DATE             NOT NULL,
    CODIGO_BARRAS    NUMBER(15, 0)    NOT NULL,
    IMAGEN_BARRAS    BLOB             NOT NULL,
    FOLIO            VARCHAR2(8)      NOT NULL,
    CONSTRAINT CREDENCIAL_CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: USER_CLIENTE.REPORTE_FISICO 
--

CREATE TABLE USER_CLIENTE.REPORTE_FISICO(
    REPORTE_FISICO_ID    NUMBER(10, 0)    NOT NULL,
    PESO                 NUMBER(5, 2)     NOT NULL,
    IMC                  NUMBER(4, 2)     NOT NULL,
    ESTATURA             NUMBER(3, 2)     NOT NULL,
    FECHA_REGISTRO       DATE             NOT NULL,
    CLIENTE_ID           NUMBER(10, 0)    NOT NULL,
    CONSTRAINT REPORTE_FISICO_PK PRIMARY KEY (REPORTE_FISICO_ID)
)
;



-- 
-- TABLE: USER_CLIENTE.SENSOR 
--

CREATE TABLE USER_CLIENTE.SENSOR(
    SENSOR_ID       NUMBER(10, 0)    NOT NULL,
    NUM_SERIE       VARCHAR2(20)     NOT NULL,
    FECHA_COMPRA    DATE             NOT NULL,
    MARCA           VARCHAR2(40)     NOT NULL,
    CLIENTE_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT SENSOR_PK PRIMARY KEY (SENSOR_ID)
)
;



-- 
-- TABLE: USER_CLIENTE.SESION 
--

CREATE TABLE USER_CLIENTE.SESION(
    SESION_ID             NUMBER(10, 0)    NOT NULL,
    NUM_SESION_CLIENTE    NUMBER(10, 0)    NOT NULL,
    FECHA_INICIO          DATE             NOT NULL,
    FECHA_FIN             DATE             NOT NULL,
    TIPO_SESION           CHAR(1)          NOT NULL,
    CLIENTE_ID            NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID           NUMBER(10, 0),
    SALA_ID               NUMBER(10, 0),
    SENSOR_ID             NUMBER(10, 0),
    CONSTRAINT SESION_PK PRIMARY KEY (SESION_ID)
)
;



-- 
-- TABLE: USER_EMPLEADO.ADMINISTRATIVO 
--

CREATE TABLE USER_EMPLEADO.ADMINISTRATIVO(
    EMPLEADO_ID            NUMBER(10, 0)    NOT NULL,
    LOGIN                  VARCHAR2(40)     NOT NULL,
    PASSWORD               VARCHAR2(255)    NOT NULL,
    ROL                    VARCHAR2(40)     NOT NULL,
    CERTIFICADO_DIGITAL    BLOB             NOT NULL,
    CONSTRAINT ADMINISTRATIVO_PK PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: USER_EMPLEADO.EMPLEADO 
--

CREATE TABLE USER_EMPLEADO.EMPLEADO(
    EMPLEADO_ID         NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERTNO         VARCHAR2(40),
    CURP                VARCHAR2(18)     NOT NULL,
    NUM_TRABAJADOR      NUMBER(10, 0)    NOT NULL,
    RFC                 VARCHAR2(15)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    EMAIL               VARCHAR2(100)    NOT NULL,
    FOTO                BLOB             NOT NULL,
    TIPO                CHAR(1)          NOT NULL,
    PUESTO_ID           NUMBER(10, 0)    NOT NULL,
    GIMNASIO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: USER_EMPLEADO.HUELLA_DIGITAL 
--

CREATE TABLE USER_EMPLEADO.HUELLA_DIGITAL(
    EMPLEADO_ID          NUMBER(10, 0)    NOT NULL,
    PULGAR_DERECHO       BLOB,
    INDICE_DERECHO       BLOB,
    MEDIO_DERECHO        BLOB,
    ANULAR_DERECHO       BLOB,
    MENIQUE_DERECHO      BLOB,
    PULGAR_IZQUIERDO     BLOB,
    INDICE_IZQUIERDO     BLOB,
    MEDIO_IZQUIERDO      BLOB,
    ANULAR_IZQUIERDO     BLOB,
    MENIQUE_IZQUIERDO    BLOB,
    CONSTRAINT HUELLA_DIGITAL_PK PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: USER_EMPLEADO.INSTRUCTOR 
--

CREATE TABLE USER_EMPLEADO.INSTRUCTOR(
    EMPLEADO_ID           NUMBER(10, 0)    NOT NULL,
    ANIOS_EXPERIENCIA     NUMBER(2, 0)     NOT NULL,
    CEDULA_PREFESIONAL    NUMBER(10, 0)    NOT NULL,
    SUPLENTE_ID           NUMBER(10, 0),
    CONSTRAINT INSTRUCTOR_PK PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: USER_EMPLEADO.PUESTO 
--

CREATE TABLE USER_EMPLEADO.PUESTO(
    PUESTO_ID      NUMBER(10, 0)    NOT NULL,
    NOMBRE         VARCHAR2(40)     NOT NULL,
    CLAVE          VARCHAR2(10)     NOT NULL,
    DESCRIPCION    VARCHAR2(255)    NOT NULL,
    CONSTRAINT PUESTO_ID_PK PRIMARY KEY (PUESTO_ID)
)
;



-- 
-- TABLE: USER_EMPLEADO.URLS 
--

CREATE TABLE USER_EMPLEADO.URLS(
    URL_ID         NUMBER(10, 0)    NOT NULL,
    URL            VARCHAR2(255)    NOT NULL,
    EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT URLS_PK PRIMARY KEY (URL_ID)
)
;



-- 
-- TABLE: USER_INFRAESTRUCTURA.DISPOSITIVO_SESION 
--

CREATE TABLE USER_INFRAESTRUCTURA.DISPOSITIVO_SESION(
    DISPOSITIVO_SESION_ID    NUMBER(10, 0)    NOT NULL,
    DISPOSITIVO_ID           NUMBER(10, 0)    NOT NULL,
    SESION_ID                NUMBER(10, 0)    NOT NULL,
    CONSTRAINT APARTO_SESION_PK PRIMARY KEY (DISPOSITIVO_SESION_ID)
)
;



-- 
-- TABLE: USER_ADMINISTRADOR.CLIENTES_GIMNASIO 
--

ALTER TABLE USER_ADMINISTRADOR.CLIENTES_GIMNASIO ADD CONSTRAINT CLIENTES_GIMNASIO_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES USER_CLIENTE.CLIENTE(CLIENTE_ID)
;

ALTER TABLE USER_ADMINISTRADOR.CLIENTES_GIMNASIO ADD CONSTRAINT CLIENTES_GIMNASIO_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES USER_ADMINISTRADOR.GIMNASIO(GIMNASIO_ID)
;


-- 
-- TABLE: USER_ADMINISTRADOR.DISPOSITIVO 
--

ALTER TABLE USER_ADMINISTRADOR.DISPOSITIVO ADD CONSTRAINT DISPOSITIVO_SALA_ID_FK 
    FOREIGN KEY (SALA_ID)
    REFERENCES USER_ADMINISTRADOR.SALA(SALA_ID)
;

ALTER TABLE USER_ADMINISTRADOR.DISPOSITIVO ADD CONSTRAINT DISPOSITIVO_STATUS_DISPOSITIVO_ID_FK 
    FOREIGN KEY (STATUS_DISPOSITIVO_ID)
    REFERENCES USER_ADMINISTRADOR.STATUS_DISPOSITIVO(STATUS_DISPOSITIVO_ID)
;

ALTER TABLE USER_ADMINISTRADOR.DISPOSITIVO ADD CONSTRAINT DISPOSITIVO_TIPO_DISPOSITIVO_ID_FK 
    FOREIGN KEY (TIPO_DISPOSITIVO_ID)
    REFERENCES USER_ADMINISTRADOR.TIPO_DISPOSITIVO(TIPO_DISPOSITIVO_ID)
;


-- 
-- TABLE: USER_ADMINISTRADOR.GIMNASIO 
--

ALTER TABLE USER_ADMINISTRADOR.GIMNASIO ADD CONSTRAINT GIMNASIO_EMPLEADO_ID_FK 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES USER_EMPLEADO.ADMINISTRATIVO(EMPLEADO_ID)
;


-- 
-- TABLE: USER_ADMINISTRADOR.HISTORICO_STATUS_DISPOSITIVO 
--

ALTER TABLE USER_ADMINISTRADOR.HISTORICO_STATUS_DISPOSITIVO ADD CONSTRAINT HISTORICO_STATUS_DISPOSITIVO_DISPOSITIVO_ID_FK 
    FOREIGN KEY (DISPOSITIVO_ID)
    REFERENCES USER_ADMINISTRADOR.DISPOSITIVO(DISPOSITIVO_ID)
;

ALTER TABLE USER_ADMINISTRADOR.HISTORICO_STATUS_DISPOSITIVO ADD CONSTRAINT HISTORICO_STATUS_DISPOSITIVO_STATUS_DISPOSITIVO_ID_FK 
    FOREIGN KEY (STATUS_DISPOSITIVO_ID)
    REFERENCES USER_ADMINISTRADOR.STATUS_DISPOSITIVO(STATUS_DISPOSITIVO_ID)
;


-- 
-- TABLE: USER_ADMINISTRADOR.MULTIMEDIA 
--

ALTER TABLE USER_ADMINISTRADOR.MULTIMEDIA ADD CONSTRAINT MULTIMEDIA_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES USER_ADMINISTRADOR.GIMNASIO(GIMNASIO_ID)
;


-- 
-- TABLE: USER_ADMINISTRADOR.SALA 
--

ALTER TABLE USER_ADMINISTRADOR.SALA ADD CONSTRAINT SALA_EMPLEADO_ID_FK 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES USER_EMPLEADO.ADMINISTRATIVO(EMPLEADO_ID)
;

ALTER TABLE USER_ADMINISTRADOR.SALA ADD CONSTRAINT SALA_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES USER_ADMINISTRADOR.GIMNASIO(GIMNASIO_ID)
;


-- 
-- TABLE: USER_ADMINISTRADOR.SALA_DISCIPLINA 
--

ALTER TABLE USER_ADMINISTRADOR.SALA_DISCIPLINA ADD CONSTRAINT SALA_DISCIPLINA_DISCIPLINA_ID_FK 
    FOREIGN KEY (DISCIPLINA_ID)
    REFERENCES USER_ADMINISTRADOR.DISCIPLINA(DISCIPLINA_ID)
;

ALTER TABLE USER_ADMINISTRADOR.SALA_DISCIPLINA ADD CONSTRAINT SALA_DISCIPLINA_SALA_ID_FK 
    FOREIGN KEY (SALA_ID)
    REFERENCES USER_ADMINISTRADOR.SALA(SALA_ID)
;


-- 
-- TABLE: USER_CLIENTE.BITACORA 
--

ALTER TABLE USER_CLIENTE.BITACORA ADD CONSTRAINT BITACORA_SESION_ID_FK 
    FOREIGN KEY (SESION_ID)
    REFERENCES USER_CLIENTE.SESION(SESION_ID)
;


-- 
-- TABLE: USER_CLIENTE.CREDENCIAL_CLIENTE 
--

ALTER TABLE USER_CLIENTE.CREDENCIAL_CLIENTE ADD CONSTRAINT CREDENCIAL_CLIENTE_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES USER_CLIENTE.CLIENTE(CLIENTE_ID)
;


-- 
-- TABLE: USER_CLIENTE.REPORTE_FISICO 
--

ALTER TABLE USER_CLIENTE.REPORTE_FISICO ADD CONSTRAINT REPORTE_FISICO_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES USER_CLIENTE.CLIENTE(CLIENTE_ID)
;


-- 
-- TABLE: USER_CLIENTE.SENSOR 
--

ALTER TABLE USER_CLIENTE.SENSOR ADD CONSTRAINT SENSOR_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES USER_CLIENTE.CLIENTE(CLIENTE_ID)
;


-- 
-- TABLE: USER_CLIENTE.SESION 
--

ALTER TABLE USER_CLIENTE.SESION ADD CONSTRAINT SESION_CLIENTE_ID_FK 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES USER_CLIENTE.CLIENTE(CLIENTE_ID)
;

ALTER TABLE USER_CLIENTE.SESION ADD CONSTRAINT SESION_EMPLEADO_ID_FK 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES USER_EMPLEADO.INSTRUCTOR(EMPLEADO_ID)
;

ALTER TABLE USER_CLIENTE.SESION ADD CONSTRAINT SESION_SALA_ID_FK 
    FOREIGN KEY (SALA_ID)
    REFERENCES USER_ADMINISTRADOR.SALA(SALA_ID)
;

ALTER TABLE USER_CLIENTE.SESION ADD CONSTRAINT SESION_SENSOR_ID_FK 
    FOREIGN KEY (SENSOR_ID)
    REFERENCES USER_CLIENTE.SENSOR(SENSOR_ID)
;


-- 
-- TABLE: USER_EMPLEADO.ADMINISTRATIVO 
--

ALTER TABLE USER_EMPLEADO.ADMINISTRATIVO ADD CONSTRAINT ADMINISTRATIVO_EMPLEADO_ID_FK 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES USER_EMPLEADO.EMPLEADO(EMPLEADO_ID)
;


-- 
-- TABLE: USER_EMPLEADO.EMPLEADO 
--

ALTER TABLE USER_EMPLEADO.EMPLEADO ADD CONSTRAINT EMPLEADO_GIMNASIO_ID_FK 
    FOREIGN KEY (GIMNASIO_ID)
    REFERENCES USER_ADMINISTRADOR.GIMNASIO(GIMNASIO_ID)
;

ALTER TABLE USER_EMPLEADO.EMPLEADO ADD CONSTRAINT EMPLEADO_PUESTO_ID_FK 
    FOREIGN KEY (PUESTO_ID)
    REFERENCES USER_EMPLEADO.PUESTO(PUESTO_ID)
;


-- 
-- TABLE: USER_EMPLEADO.HUELLA_DIGITAL 
--

ALTER TABLE USER_EMPLEADO.HUELLA_DIGITAL ADD CONSTRAINT HUELLA_DIGITAL_EMPLEADO_ID_FK 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES USER_EMPLEADO.EMPLEADO(EMPLEADO_ID)
;


-- 
-- TABLE: USER_EMPLEADO.INSTRUCTOR 
--

ALTER TABLE USER_EMPLEADO.INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_EMPLEADO_ID_FK 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES USER_EMPLEADO.EMPLEADO(EMPLEADO_ID)
;

ALTER TABLE USER_EMPLEADO.INSTRUCTOR ADD CONSTRAINT INSTRUCTOR_SUPLENTE_ID_FK 
    FOREIGN KEY (SUPLENTE_ID)
    REFERENCES USER_EMPLEADO.INSTRUCTOR(EMPLEADO_ID)
;


-- 
-- TABLE: USER_EMPLEADO.URLS 
--

ALTER TABLE USER_EMPLEADO.URLS ADD CONSTRAINT URLS_EMPLEADO_ID_FK 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES USER_EMPLEADO.INSTRUCTOR(EMPLEADO_ID)
;


-- 
-- TABLE: USER_INFRAESTRUCTURA.DISPOSITIVO_SESION 
--

ALTER TABLE USER_INFRAESTRUCTURA.DISPOSITIVO_SESION ADD CONSTRAINT DISPOSITIVO_SESION_DISPOSITIVO_ID_FK 
    FOREIGN KEY (DISPOSITIVO_ID)
    REFERENCES USER_ADMINISTRADOR.DISPOSITIVO(DISPOSITIVO_ID)
;

ALTER TABLE USER_INFRAESTRUCTURA.DISPOSITIVO_SESION ADD CONSTRAINT DISPOSITIVO_SESION_SESION_ID_FK 
    FOREIGN KEY (SESION_ID)
    REFERENCES USER_CLIENTE.SESION(SESION_ID)
;


