

alter user user_infraestructura quota unlimited on TBS_INDEX;
alter user user_empleado quota unlimited on TBS_INDEX;
alter user user_cliente quota unlimited on TBS_INDEX;

CREATE UNIQUE INDEX USER_INFRAESTRUCTURA.DISCIPLINA_CLAVE_UK ON USER_INFRAESTRUCTURA.DISCIPLINA(CLAVE)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_INFRAESTRUCTURA.GIMNASIO_FOLIO_UX ON USER_INFRAESTRUCTURA.GIMNASIO(FOLIO)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_INFRAESTRUCTURA.GIMNASIO_NOMBRE_IX ON USER_INFRAESTRUCTURA.GIMNASIO(UPPER(NOMBRE))
TABLESPACE TBS_INDEX;

CREATE INDEX USER_INFRAESTRUCTURA.SALA_CLAVE_IX ON USER_INFRAESTRUCTURA.SALA(CLAVE)
TABLESPACE TBS_INDEX;

CREATE UNIQUE INDEX USER_INFRAESTRUCTURA.STATUS_DISPOSITIVO_CLAVE_UK ON USER_INFRAESTRUCTURA.STATUS_DISPOSITIVO(CLAVE)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_INFRAESTRUCTURA.TIPO_DISPOSITIVO_NOMBRE_IX ON USER_INFRAESTRUCTURA.TIPO_DISPOSITIVO(UPPER(NOMBRE))
TABLESPACE TBS_INDEX;

CREATE INDEX USER_CLIENTE.FECHA_IX ON USER_CLIENTE.BITACORA(FECHA_HORA_REGISTRO)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_CLIENTE.CLIENTE_USERNAME_UK ON USER_CLIENTE.CLIENTE(USERNAME)
TABLESPACE TBS_INDEX;

CREATE UNIQUE INDEX USER_CLIENTE.CLIENTE_CURP_UK ON USER_CLIENTE.CLIENTE(CURP)
TABLESPACE TBS_INDEX;

CREATE UNIQUE INDEX USER_CLIENTE.CREDENCIAL_CLIENTE_CODIGO_BARRAS_UK ON USER_CLIENTE.CREDENCIAL_CLIENTE(CODIGO_BARRAS)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_CLIENTE.CREDENCIAL_CLIENTE_FOLIO_UK ON USER_CLIENTE.CREDENCIAL_CLIENTE(FOLIO)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_CLIENTE.REPORTE_FISICO_FECHA_REGISTRO_IX ON USER_CLIENTE.REPORTE_FISICO(FECHA_REGISTRO)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_CLIENTE.SENSOR_NUM_SERIE_UK ON USER_CLIENTE.SENSOR(NUM_SERIE)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_CLIENTE.SESION_FECHA_INICIO_IX ON USER_CLIENTE.SESION(FECHA_INICIO)
TABLESPACE TBS_INDEX;

CREATE INDEX USER_CLIENTE.SESION_FECHA_FIN_IX ON USER_CLIENTE.SESION(FECHA_FIN)
TABLESPACE TBS_INDEX;

CREATE UNIQUE INDEX USER_EMPLEADO.ADMINISTRATIVO_LOGIN_UK ON USER_EMPLEADO.ADMINISTRATIVO(LOGIN)
TABLESPACE TBS_INDEX;

CREATE UNIQUE INDEX USER_EMPLEADO.EMPLEADO_CURP_UK ON USER_EMPLEADO.EMPLEADO(CURP)
TABLESPACE TBS_INDEX;

CREATE UNIQUE INDEX USER_EMPLEADO.EMPLEADO_RFC_UK ON USER_EMPLEADO.EMPLEADO(RFC)
TABLESPACE TBS_INDEX;

CREATE UNIQUE INDEX USER_EMPLEADO.EMPLEADO_EMAIL_UK ON USER_EMPLEADO.EMPLEADO(EMAIL)
TABLESPACE TBS_INDEX;

CREATE UNIQUE INDEX USER_EMPLEADO.PUESTO_CLAVE_UK ON USER_EMPLEADO.PUESTO(CLAVE)
TABLESPACE TBS_INDEX;
